src/Entity/Entities/EntityInterface.php
<?php

namespace App\Entity\Entities;

interface EntityInterface
{
    public function getId(): int;
}

src/Entity/Tag.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Entities\EntityInterface;
use App\Entity\Entities\EntityTrait;
use Doctrine\ORM\Mapping\JoinTable;
use Gedmo\SoftDeleteable\Traits\SoftDeleteableEntity;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity #(repositoryClass="App\Repository\ProductRepository")
 * @Gedmo\SoftDeleteable(timeAware=true)
 */
class Tag implements EntityInterface
{
    use EntityTrait;
    use TimestampableEntity;
    use SoftDeleteableEntity;
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Gif", mappedBy="tags")
     * @JoinTable(name="gifs_tags")
     */
    private $gifCollection;

    public function __construct()
    {
        $this->gifCollection = new ArrayCollection();
    }

    /**
     * @return mixed
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param mixed $name
     * @return self
     */
    public function setName($name): self
    {
        $this->name = $name;
        return $this;
    }

    /**
     * @return Collection
     */
    public function getGifs()
    {
        return $this->gifCollection;
    }

    public function __toString(): string
    {
        return $this->name;
    }

}

templates/tags/show.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <div class="container">
        <h2 class="mb-5">Tag : {{ tag.name }}
        </h2>
        <div class="row">
            <div class="card-columns">
                {% for gif in tag.getGifs() %}
                    <div class="mb-4">
                        <div class="card w-100 border border-secondary">
                            <img src="{{ gif.url }}" alt="" class="card-img-top">
                            <div class="card-body">
                                <a href="{{ path('app_gifs_album_view', {album: gif.album.id}) }}">Dans
                                    "{{ gif.album.title }}"</a>
                                <br>
                                {% for tag in gif.tags %}
                                    <a class="badge badge-secondary"
                                       href="{{ path('app_gifs_tag_search', {tag: tag.name}) }}">{{ tag.name }}</a>
                                {% endfor %}
                                <p><small class="text-muted">Ajouté le
                                        : {{ gif.createdAt.format('d/m/Y à H:m') }}</small></p>
                                {% if is_granted('ROLE_ADMIN') and gif.album.author == app.user %}
                                    <a href="{{ path('app_gifs_delete', {album: gif.album.id, gif: gif.id}) }}"
                                       class="btn btn-danger">Supprimer</a>
                                {% endif %}
                                {% if is_granted('ROLE_USER') %}
                                    {% if gif.isFavedBy(app.user) %}
                                        <a class="float-right btn btn-warning mb-3"
                                           href="{{ path('app_gifs_fav', {album: gif.album.id, gif: gif.id}) }}"
                                           title="Supprimer des favoris">❤</a>
                                    {% else %}
                                        <a class="float-right btn btn-outline-warning mb-3"
                                           href="{{ path('app_gifs_fav', {album: gif.album.id, gif: gif.id}) }}"
                                           title="Ajouter aux favoris">❤</a>
                                    {% endif %}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}